// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLDatVeMayBay.Data;

#nullable disable

namespace QLDatVeMayBay.Migrations
{
    [DbContext(typeof(QLDatVeMayBayContext))]
    partial class QLDatVeMayBayContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLDatVeMayBay.Models.ChuyenBay", b =>
                {
                    b.Property<int>("IDChuyenBay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDChuyenBay"));

                    b.Property<decimal>("GiaVe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("GioCatCanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GioHaCanh")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDMayBay")
                        .HasColumnType("int");

                    b.Property<int>("SanBayDen")
                        .HasColumnType("int");

                    b.Property<int>("SanBayDi")
                        .HasColumnType("int");

                    b.Property<string>("TinhTrang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDChuyenBay");

                    b.HasIndex("IDMayBay");

                    b.HasIndex("SanBayDen");

                    b.HasIndex("SanBayDi");

                    b.ToTable("ChuyenBay");
                });

            modelBuilder.Entity("QLDatVeMayBay.Models.Entities.TheThanhToan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CVV")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("EmailLienKet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HieuLuc")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Loai")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayLienKet")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoThe")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenHienThi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNganHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTrenThe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenVi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TheThanhToanId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("TheThanhToanId");

                    b.ToTable("TheThanhToan");
                });

            modelBuilder.Entity("QLDatVeMayBay.Models.GheNgoi", b =>
                {
                    b.Property<int>("IDGhe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDGhe"));

                    b.Property<string>("HangGhe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IDChuyenBay")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IDGhe");

                    b.HasIndex("IDChuyenBay");

                    b.ToTable("GheNgoi");
                });

            modelBuilder.Entity("QLDatVeMayBay.Models.HoanTien", b =>
                {
                    b.Property<int>("IDHoanTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDHoanTien"));

                    b.Property<int>("IDThanhToan")
                        .HasColumnType("int");

                    b.Property<string>("LyDo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("NgayHoanTien")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTienHoan")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IDHoanTien");

                    b.HasIndex("IDThanhToan");

                    b.ToTable("HoanTien");
                });

            modelBuilder.Entity("QLDatVeMayBay.Models.LoaiMayBay", b =>
                {
                    b.Property<int>("LoaiMayBayId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoaiMayBayId"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TongSoGhe")
                        .HasColumnType("int");

                    b.HasKey("LoaiMayBayId");

                    b.ToTable("LoaiMayBay");
                });

            modelBuilder.Entity("QLDatVeMayBay.Models.MaXacNhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianHetHan")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MaXacNhan");
                });

            modelBuilder.Entity("QLDatVeMayBay.Models.MayBay", b =>
                {
                    b.Property<int>("IDMayBay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDMayBay"));

                    b.Property<int>("LoaiMayBayId")
                        .HasColumnType("int");

                    b.Property<int?>("LoaiMayBayId1")
                        .HasColumnType("int");

                    b.Property<string>("TenHangHK")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IDMayBay");

                    b.HasIndex("LoaiMayBayId");

                    b.HasIndex("LoaiMayBayId1");

                    b.ToTable("MayBay");
                });

            modelBuilder.Entity("QLDatVeMayBay.Models.NguoiDung", b =>
                {
                    b.Property<int>("IDNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDNguoiDung"));

                    b.Property<string>("CCCD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QuocTich")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDNguoiDung");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("QLDatVeMayBay.Models.SanBay", b =>
                {
                    b.Property<int>("IDSanBay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDSanBay"));

                    b.Property<string>("DiaDiem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenSanBay")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IDSanBay");

                    b.ToTable("SanBay");
                });

            modelBuilder.Entity("QLDatVeMayBay.Models.TaiKhoan", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLanDangNhapSai")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianBiKhoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThaiTK")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TenDangNhap");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("QLDatVeMayBay.Models.ThanhToan", b =>
                {
                    b.Property<int>("IDThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDThanhToan"));

                    b.Property<int>("IDVe")
                        .HasColumnType("int");

                    b.Property<string>("PhuongThuc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ThoiGianGiaoDich")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThaiThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDThanhToan");

                    b.HasIndex("IDVe");

                    b.ToTable("ThanhToan");
                });

            modelBuilder.Entity("QLDatVeMayBay.Models.VeMayBay", b =>
                {
                    b.Property<int>("IDVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDVe"));

                    b.Property<string>("HangGhe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDChuyenBay")
                        .HasColumnType("int");

                    b.Property<int>("IDGhe")
                        .HasColumnType("int");

                    b.Property<int>("IDNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("IDTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("LoaiVe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NguoiDungIDNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("TaiKhoanTenDangNhap")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ThanhToanIDThanhToan")
                        .HasColumnType("int");

                    b.Property<string>("TheThanhToanId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ThoiGianDat")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThaiVe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDVe");

                    b.HasIndex("IDChuyenBay");

                    b.HasIndex("IDGhe");

                    b.HasIndex("IDNguoiDung");

                    b.HasIndex("NguoiDungIDNguoiDung");

                    b.HasIndex("TaiKhoanTenDangNhap");

                    b.HasIndex("ThanhToanIDThanhToan");

                    b.HasIndex("TheThanhToanId");

                    b.ToTable("VeMayBay");
                });

            modelBuilder.Entity("QLDatVeMayBay.Models.ChuyenBay", b =>
                {
                    b.HasOne("QLDatVeMayBay.Models.MayBay", "MayBay")
                        .WithMany()
                        .HasForeignKey("IDMayBay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLDatVeMayBay.Models.SanBay", "SanBayDenInfo")
                        .WithMany()
                        .HasForeignKey("SanBayDen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLDatVeMayBay.Models.SanBay", "SanBayDiInfo")
                        .WithMany()
                        .HasForeignKey("SanBayDi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MayBay");

                    b.Navigation("SanBayDenInfo");

                    b.Navigation("SanBayDiInfo");
                });

            modelBuilder.Entity("QLDatVeMayBay.Models.Entities.TheThanhToan", b =>
                {
                    b.HasOne("QLDatVeMayBay.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLDatVeMayBay.Models.Entities.TheThanhToan", null)
                        .WithMany("DanhSach")
                        .HasForeignKey("TheThanhToanId");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QLDatVeMayBay.Models.GheNgoi", b =>
                {
                    b.HasOne("QLDatVeMayBay.Models.ChuyenBay", "ChuyenBay")
                        .WithMany()
                        .HasForeignKey("IDChuyenBay")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenBay");
                });

            modelBuilder.Entity("QLDatVeMayBay.Models.HoanTien", b =>
                {
                    b.HasOne("QLDatVeMayBay.Models.ThanhToan", "ThanhToan")
                        .WithMany()
                        .HasForeignKey("IDThanhToan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThanhToan");
                });

            modelBuilder.Entity("QLDatVeMayBay.Models.MayBay", b =>
                {
                    b.HasOne("QLDatVeMayBay.Models.LoaiMayBay", "LoaiMayBay")
                        .WithMany()
                        .HasForeignKey("LoaiMayBayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLDatVeMayBay.Models.LoaiMayBay", null)
                        .WithMany("MayBays")
                        .HasForeignKey("LoaiMayBayId1");

                    b.Navigation("LoaiMayBay");
                });

            modelBuilder.Entity("QLDatVeMayBay.Models.NguoiDung", b =>
                {
                    b.HasOne("QLDatVeMayBay.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("NguoiDung")
                        .HasForeignKey("QLDatVeMayBay.Models.NguoiDung", "TenDangNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QLDatVeMayBay.Models.ThanhToan", b =>
                {
                    b.HasOne("QLDatVeMayBay.Models.VeMayBay", "VeMayBay")
                        .WithMany()
                        .HasForeignKey("IDVe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VeMayBay");
                });

            modelBuilder.Entity("QLDatVeMayBay.Models.VeMayBay", b =>
                {
                    b.HasOne("QLDatVeMayBay.Models.ChuyenBay", "ChuyenBay")
                        .WithMany()
                        .HasForeignKey("IDChuyenBay")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLDatVeMayBay.Models.GheNgoi", "Ghe")
                        .WithMany()
                        .HasForeignKey("IDGhe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLDatVeMayBay.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("IDNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLDatVeMayBay.Models.NguoiDung", null)
                        .WithMany("VeMayBays")
                        .HasForeignKey("NguoiDungIDNguoiDung");

                    b.HasOne("QLDatVeMayBay.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanTenDangNhap");

                    b.HasOne("QLDatVeMayBay.Models.ThanhToan", "ThanhToan")
                        .WithMany()
                        .HasForeignKey("ThanhToanIDThanhToan");

                    b.HasOne("QLDatVeMayBay.Models.Entities.TheThanhToan", "TheThanhToan")
                        .WithMany()
                        .HasForeignKey("TheThanhToanId");

                    b.Navigation("ChuyenBay");

                    b.Navigation("Ghe");

                    b.Navigation("NguoiDung");

                    b.Navigation("TaiKhoan");

                    b.Navigation("ThanhToan");

                    b.Navigation("TheThanhToan");
                });

            modelBuilder.Entity("QLDatVeMayBay.Models.Entities.TheThanhToan", b =>
                {
                    b.Navigation("DanhSach");
                });

            modelBuilder.Entity("QLDatVeMayBay.Models.LoaiMayBay", b =>
                {
                    b.Navigation("MayBays");
                });

            modelBuilder.Entity("QLDatVeMayBay.Models.NguoiDung", b =>
                {
                    b.Navigation("VeMayBays");
                });

            modelBuilder.Entity("QLDatVeMayBay.Models.TaiKhoan", b =>
                {
                    b.Navigation("NguoiDung");
                });
#pragma warning restore 612, 618
        }
    }
}
